module.exports = '<td class="mhgame-result">2019-03-24</td>' +
  '<td class="mhgame-result"><a href="/Patch_9.5" class="to_hasTooltip" title="Patch 9.5" data-to-id="Patch_9_2e-5" data-to-titles="Patch 9.5||Tooltip:Patch 9.5" data-to-flags="fieM">9.5</a></td>' +
  '<td class="mhgame-result"><a href="/FlyQuest" title="FlyQuest" class="to_hasTooltip" data-to-id="FlyQuest" data-to-titles="FlyQuest||Tooltip:FlyQuest" data-to-flags="fiem"><img alt="FlyQuestlogo std.png" src="https://gamepedia.cursecdn.com/lolesports_gamepedia_en/7/7d/FlyQuestlogo_std.png?version=d45ae8e52198ae93aa5c529d3d3060c2" decoding="async" width="60" height="25"></a></td>' +
  '<td class="mhgame-result"><a href="/Golden_Guardians" title="Golden Guardians" class="to_hasTooltip" data-to-id="Golden_Guardians" data-to-titles="Golden Guardians||Tooltip:Golden Guardians" data-to-flags="fiem"><img alt="Golden Guardianslogo std.png" src="https://gamepedia.cursecdn.com/lolesports_gamepedia_en/0/09/Golden_Guardianslogo_std.png?version=6a58e7fe7c376aaf7e31262a1f35da09" decoding="async" width="60" height="25"></a></td>' +
  '<td class="mhgame-result"><a href="/FlyQuest" title="FlyQuest" class="to_hasTooltip" data-to-id="FlyQuest" data-to-titles="FlyQuest||Tooltip:FlyQuest" data-to-flags="fiem"><img alt="FlyQuestlogo std.png" src="https://gamepedia.cursecdn.com/lolesports_gamepedia_en/7/7d/FlyQuestlogo_std.png?version=d45ae8e52198ae93aa5c529d3d3060c2" decoding="async" width="60" height="25"></a></td>' +
  '<td class="mhgame-bans"><span class="sprite champion-sprite" style="background-position:-155px -78px;background-size:387px auto;width:25px;height:25px"><br></span><span class="sprite champion-sprite" style="background-position:-129px -181px;background-size:387px auto;width:25px;height:25px"><br></span><span class="sprite champion-sprite" style="background-position:-78px -181px;background-size:387px auto;width:25px;height:25px"><br></span><span class="sprite champion-sprite" style="background-position:-78px -0px;background-size:387px auto;width:25px;height:25px"><br></span><span class="sprite champion-sprite" style="background-position:-155px -129px;background-size:387px auto;width:25px;height:25px"><br></span></td>' +
  '<td class="mhgame-bans"><span class="sprite champion-sprite" style="background-position:-0px -78px;background-size:387px auto;width:25px;height:25px"><br></span><span class="sprite champion-sprite" style="background-position:-284px -233px;background-size:387px auto;width:25px;height:25px"><br></span><span class="sprite champion-sprite" style="background-position:-52px -155px;background-size:387px auto;width:25px;height:25px"><br></span><span class="sprite champion-sprite" style="background-position:-336px -207px;background-size:387px auto;width:25px;height:25px"><br></span><span class="sprite champion-sprite" style="background-position:-129px -155px;background-size:387px auto;width:25px;height:25px"><br></span></td>' +
  '<td><span class="sprite champion-sprite" style="background-position:-103px -103px;background-size:387px auto;width:25px;height:25px"><br></span><span class="sprite champion-sprite" style="background-position:-129px -129px;background-size:387px auto;width:25px;height:25px"><br></span><span class="sprite champion-sprite" style="background-position:-258px -52px;background-size:387px auto;width:25px;height:25px"><br></span><span class="sprite champion-sprite" style="background-position:-310px -26px;background-size:387px auto;width:25px;height:25px"><br></span><span class="sprite champion-sprite" style="background-position:-0px -155px;background-size:387px auto;width:25px;height:25px"><br></span></td>' +
  '<td><span class="sprite champion-sprite" style="background-position:-310px -129px;background-size:387px auto;width:25px;height:25px"><br></span><span class="sprite champion-sprite" style="background-position:-336px -52px;background-size:387px auto;width:25px;height:25px"><br></span><span class="sprite champion-sprite" style="background-position:-181px -155px;background-size:387px auto;width:25px;height:25px"><br></span><span class="sprite champion-sprite" style="background-position:-129px -103px;background-size:387px auto;width:25px;height:25px"><br></span><span class="sprite champion-sprite" style="background-position:-362px -0px;background-size:387px auto;width:25px;height:25px"><br></span></td>' +
  '<td><a href="/V1per" class="to_hasTooltip" title="V1per" data-to-id="V1per" data-to-titles="V1per||Tooltip:V1per" data-to-flags="fieM">V1per</a>, <a href="/Maxi" class="to_hasTooltip" title="Maxi" data-to-id="Maxi" data-to-titles="Maxi||Tooltip:Maxi" data-to-flags="fieM">Maxi</a>, <a href="/Pobelter" class="to_hasTooltip" title="Pobelter" data-to-id="Pobelter" data-to-titles="Pobelter||Tooltip:Pobelter" data-to-flags="fieM">Pobelter</a>, <a href="/WildTurtle" class="to_hasTooltip" title="WildTurtle" data-to-id="WildTurtle" data-to-titles="WildTurtle||Tooltip:WildTurtle" data-to-flags="fieM">WildTurtle</a>, <a href="/JayJ" class="to_hasTooltip" title="JayJ" data-to-id="JayJ" data-to-titles="JayJ||Tooltip:JayJ" data-to-flags="fieM">JayJ</a></td>' +
  '<td><a href="/Hauntzer" class="to_hasTooltip" title="Hauntzer" data-to-id="Hauntzer" data-to-titles="Hauntzer||Tooltip:Hauntzer" data-to-flags="fieM">Hauntzer</a>, <a href="/Contractz" class="to_hasTooltip" title="Contractz" data-to-id="Contractz" data-to-titles="Contractz||Tooltip:Contractz" data-to-flags="fieM">Contractz</a>, <a href="/Froggen" class="to_hasTooltip" title="Froggen" data-to-id="Froggen" data-to-titles="Froggen||Tooltip:Froggen" data-to-flags="fieM">Froggen</a>, <a href="/Deftly" class="to_hasTooltip" title="Deftly" data-to-id="Deftly" data-to-titles="Deftly||Tooltip:Deftly" data-to-flags="fieM">Deftly</a>, <a href="/Olleh" class="to_hasTooltip" title="Olleh" data-to-id="Olleh" data-to-titles="Olleh||Tooltip:Olleh" data-to-flags="fieM">Olleh</a></td>' +
  '<td><a href="/LCS/2019_Season/Spring_Season/Scoreboards/Week_9" class="to_hasTooltip" title="LCS/2019 Season/Spring Season/Scoreboards/Week 9" data-to-id="LCS_2f-2019_Season_2f-Spring_Season_2f-Scoreboards_2f-Week_9" data-to-titles="LCS/2019 Season/Spring Season/Scoreboards/Week 9||Tooltip:LCS/2019 Season/Spring Season/Scoreboards/Week 9" data-to-flags="fieM">SB</a></td>' +
  '<td><a target="_blank" rel="nofollow noreferrer noopener" class="external text" href="https://matchhistory.euw.leagueoflegends.com/en/#match-details/ESPORTSTMNT01/1074560?gameHash=6a89b0a79afa77c8&amp;tab=overview">MH</a></td>' +
  '<td><a target="_blank" rel="nofollow noreferrer noopener" class="external text" href="https://youtu.be/qBCaf4I9Xjk?t=128">VOD</a></td>';
